using System.IO.Compression;
using System.Text;

using ArchLucid.Application.Marketing;

using FluentAssertions;

namespace ArchLucid.Application.Tests.Marketing;

[Trait("Category", "Unit")]
public sealed class EvidencePackBuilderTests
{
    [Fact]
    public async Task BuildAsync_PrependsAutoGeneratedReadmeAndPreservesSourceOrder()
    {
        StubSourceProvider provider = new(
        [
            new EvidencePackEntry("DPA-template.md", "dpa body"u8.ToArray()),
            new EvidencePackEntry("SUBPROCESSORS.md", "subprocessor body"u8.ToArray()),
        ]);

        EvidencePackBuilder sut = new(provider, TimeProvider.System);

        EvidencePackArtifact artifact = await sut.BuildAsync(CancellationToken.None);

        IReadOnlyList<string> entriesInZip = ListZipEntryNames(artifact.Bytes);

        entriesInZip.Should().Equal(["README.md", "DPA-template.md", "SUBPROCESSORS.md"]);
        artifact.ContentType.Should().Be("application/zip");
    }

    [Fact]
    public async Task BuildAsync_ReadmeListsEverySourceFileAndStopAndAskBoundaries()
    {
        StubSourceProvider provider = new(
        [
            new EvidencePackEntry("DPA-template.md", "dpa"u8.ToArray()),
            new EvidencePackEntry("PEN_TEST_SOW_2026_Q2.md", "sow"u8.ToArray()),
        ]);

        EvidencePackBuilder sut = new(provider, TimeProvider.System);

        EvidencePackArtifact artifact = await sut.BuildAsync(CancellationToken.None);

        string readme = ReadZipEntryAsString(artifact.Bytes, "README.md");

        readme.Should().Contain("DPA-template.md");
        readme.Should().Contain("PEN_TEST_SOW_2026_Q2.md");
        readme.Should().Contain("REDACTED");
        readme.Should().Contain("PGP");
    }

    [Fact]
    public async Task BuildAsync_EtagDependsOnlyOnSourceContentNotOnBuildTimestamp()
    {
        StubSourceProvider provider = new(
        [
            new EvidencePackEntry("a.md", "alpha"u8.ToArray()),
            new EvidencePackEntry("b.md", "beta"u8.ToArray()),
        ]);

        FakeTimeProvider clock1 = new(new DateTimeOffset(2026, 1, 1, 0, 0, 0, TimeSpan.Zero));
        FakeTimeProvider clock2 = new(new DateTimeOffset(2026, 6, 30, 12, 30, 0, TimeSpan.Zero));

        EvidencePackArtifact a1 = await new EvidencePackBuilder(provider, clock1).BuildAsync();
        EvidencePackArtifact a2 = await new EvidencePackBuilder(provider, clock2).BuildAsync();

        a2.ETag.Should().Be(a1.ETag);
    }

    [Fact]
    public async Task BuildAsync_ProducesByteIdenticalZipForUnchangedSources()
    {
        StubSourceProvider provider = new(
        [
            new EvidencePackEntry("a.md", "alpha"u8.ToArray()),
            new EvidencePackEntry("b.md", "beta"u8.ToArray()),
        ]);

        EvidencePackArtifact first = await new EvidencePackBuilder(provider, TimeProvider.System).BuildAsync();
        EvidencePackArtifact second = await new EvidencePackBuilder(provider, TimeProvider.System).BuildAsync();

        second.Bytes.Should().Equal(first.Bytes);
        second.ETag.Should().Be(first.ETag);
    }

    [Fact]
    public async Task BuildAsync_EtagMatchesEvidencePackEtagComputeOverSourceEntriesOnly()
    {
        EvidencePackEntry[] sources =
        [
            new("a.md", "alpha"u8.ToArray()),
            new("b.md", "beta"u8.ToArray()),
        ];

        StubSourceProvider provider = new(sources);
        EvidencePackArtifact artifact = await new EvidencePackBuilder(provider, TimeProvider.System).BuildAsync();

        string expected = EvidencePackEtag.Compute(sources);
        artifact.ETag.Should().Be(expected);
    }

    [Fact]
    public async Task BuildAsync_ThrowsWhenProviderReturnsNoEntries()
    {
        StubSourceProvider provider = new([]);
        EvidencePackBuilder sut = new(provider, TimeProvider.System);

        Func<Task> act = async () => await sut.BuildAsync(CancellationToken.None);
        await act.Should().ThrowAsync<InvalidOperationException>();
    }

    private static IReadOnlyList<string> ListZipEntryNames(byte[] zipBytes)
    {
        using MemoryStream ms = new(zipBytes);
        using ZipArchive archive = new(ms, ZipArchiveMode.Read);

        return [.. archive.Entries.Select(e => e.FullName)];
    }

    private static string ReadZipEntryAsString(byte[] zipBytes, string entryName)
    {
        using MemoryStream ms = new(zipBytes);
        using ZipArchive archive = new(ms, ZipArchiveMode.Read);

        ZipArchiveEntry? entry = archive.GetEntry(entryName) ??
            throw new InvalidOperationException($"Entry {entryName} not found in ZIP.");

        using Stream stream = entry.Open();
        using StreamReader reader = new(stream, Encoding.UTF8);
        return reader.ReadToEnd();
    }

    private sealed class StubSourceProvider(IReadOnlyList<EvidencePackEntry> entries) : IEvidencePackSourceProvider
    {
        public Task<IReadOnlyList<EvidencePackEntry>> GetEntriesAsync(CancellationToken cancellationToken = default) =>
            Task.FromResult(entries);
    }

    private sealed class FakeTimeProvider(DateTimeOffset now) : TimeProvider
    {
        public override DateTimeOffset GetUtcNow() => now;
    }
}
