using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

namespace ArchiForge.ArtifactSynthesis.Docx;

/// <summary>
/// Builds an in-memory branded .docx when <c>architecture-template.docx</c> is not on disk.
/// Drop a customized file under <c>Docx/Templates/</c> (copied to output) to override.
/// </summary>
public static class BrandedArchitectureTemplateGenerator
{
    public static byte[] CreateTemplateBytes()
    {
        using MemoryStream ms = new MemoryStream();
        using (WordprocessingDocument doc = WordprocessingDocument.Create(ms, WordprocessingDocumentType.Document, true))
        {
            MainDocumentPart main = doc.AddMainDocumentPart();
            main.Document = new Document(new Body());

            HeaderPart headerPart = main.AddNewPart<HeaderPart>();
            string headerRelId = main.GetIdOfPart(headerPart);
            headerPart.Header = new Header(
                new Paragraph(
                    new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
                    new Run(
                        new RunProperties(
                            new RunFonts { Ascii = "Calibri", HighAnsi = "Calibri" },
                            new Bold(),
                            new FontSize { Val = "28" },
                            new Color { Val = "2F5496" }),
                        new Text("ArchiForge"))),
                new Paragraph(
                    new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
                    new Run(
                        new RunProperties(
                            new RunFonts { Ascii = "Calibri", HighAnsi = "Calibri" },
                            new FontSize { Val = "22" },
                            new Color { Val = "595959" }),
                        new Text("Architecture intelligence · Boardroom package"))));

            FooterPart footerPart = main.AddNewPart<FooterPart>();
            string footerRelId = main.GetIdOfPart(footerPart);
            footerPart.Footer = new Footer(
                new Paragraph(
                    new ParagraphProperties(new Justification { Val = JustificationValues.Center }),
                    new Run(
                        new RunProperties(new FontSize { Val = "18" }, new Color { Val = "808080" }),
                        new Text("Confidential · Generated by ArchiForge"))));

            AddCustomStyles(main);

            Body body = main.Document.Body!;
            body.AppendChild(
                new SectionProperties(
                    new HeaderReference { Type = HeaderFooterValues.Default, Id = headerRelId },
                    new FooterReference { Type = HeaderFooterValues.Default, Id = footerRelId },
                    new PageSize { Width = 12240U, Height = 15840U },
                    new PageMargin
                    {
                        Top = 1440,
                        Right = 1440,
                        Bottom = 1440,
                        Left = 1440,
                        Header = 720,
                        Footer = 720
                    }));

            main.Document.Save();
        }

        return ms.ToArray();
    }

    private static void AddCustomStyles(MainDocumentPart main)
    {
        StyleDefinitionsPart stylesPart = main.AddNewPart<StyleDefinitionsPart>();
        stylesPart.Styles = new Styles(
            new DocDefaults(
                new RunPropertiesDefault(
                    new RunFonts { Ascii = "Calibri", HighAnsi = "Calibri" })),
            new Style(
                new StyleName { Val = "ArchiForge Body" },
                new BasedOn { Val = "Normal" },
                new StyleParagraphProperties(
                    new SpacingBetweenLines
                    {
                        After = "160",
                        Line = "276",
                        LineRule = LineSpacingRuleValues.Auto
                    }))
            {
                Type = StyleValues.Paragraph,
                StyleId = DocxStyleIds.BodyText
            },
            new Style(
                new StyleName { Val = "ArchiForge Table Header" },
                new BasedOn { Val = "Normal" },
                new StyleRunProperties(new Bold()),
                new StyleParagraphProperties(new Justification { Val = JustificationValues.Center }))
            {
                Type = StyleValues.Paragraph,
                StyleId = DocxStyleIds.TableHeader
            });
    }
}
