using System.IO.Compression;
using System.Net;
using System.Net.Http.Headers;

using ArchLucid.Application.Marketing;

using FluentAssertions;

namespace ArchLucid.Api.Tests;

[Trait("Category", "Integration")]
public sealed class TrustCenterEvidencePackEndpointTests
{
    private const string EndpointPath = "/v1/marketing/trust-center/evidence-pack.zip";

    [Fact]
    public async Task Get_ReturnsZipWithEveryExpectedEntryAndAutoGeneratedReadme()
    {
        await using ArchLucidApiFactory factory = new();
        HttpClient client = factory.CreateClient();

        HttpResponseMessage response = await client.GetAsync(EndpointPath);

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        response.Content.Headers.ContentType?.MediaType.Should().Be("application/zip");

        byte[] zipBytes = await response.Content.ReadAsByteArrayAsync();
        IReadOnlyList<string> entryNames = ListZipEntryNames(zipBytes);

        entryNames.Should().Contain("README.md", "the builder auto-generates an index README.");

        foreach (string canonical in EmbeddedResourceEvidencePackSourceProvider.OrderedZipNames)
        {
            entryNames.Should().Contain(canonical,
                $"{canonical} is part of the canonical Trust Center evidence pack.");
        }
    }

    [Fact]
    public async Task Get_DoesNotIncludePenTestRedactedSummaryOrPgpKey()
    {
        await using ArchLucidApiFactory factory = new();
        HttpClient client = factory.CreateClient();

        HttpResponseMessage response = await client.GetAsync(EndpointPath);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        byte[] zipBytes = await response.Content.ReadAsByteArrayAsync();
        IReadOnlyList<string> entryNames = ListZipEntryNames(zipBytes);

        entryNames.Should().NotContain(name => name.Contains("REDACTED", StringComparison.OrdinalIgnoreCase),
            "the redacted pen-test summary is V1.1-gated per PENDING_QUESTIONS Q10.");

        entryNames.Should().NotContain(name => name.Contains("PGP", StringComparison.OrdinalIgnoreCase),
            "the PGP key publication is V1.1-gated.");
    }

    [Fact]
    public async Task Get_IsAnonymousAndDoesNotRequireAuthHeaders()
    {
        await using ArchLucidApiFactory factory = new();
        HttpClient client = factory.CreateClient();

        client.DefaultRequestHeaders.Authorization = null;
        HttpResponseMessage response = await client.GetAsync(EndpointPath);

        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "the Trust Center evidence pack is a public procurement artefact (anonymous access).");
    }

    [Fact]
    public async Task Get_SetsETagAndOneHourPublicCacheControlHeaders()
    {
        await using ArchLucidApiFactory factory = new();
        HttpClient client = factory.CreateClient();

        HttpResponseMessage response = await client.GetAsync(EndpointPath);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        response.Headers.ETag.Should().NotBeNull();
        string etag = response.Headers.ETag!.Tag;
        etag.Should().StartWith("\"").And.EndWith("\"");
        etag.Length.Should().Be(2 + 64);

        CacheControlHeaderValue? cacheControl = response.Headers.CacheControl;
        cacheControl.Should().NotBeNull();
        cacheControl!.Public.Should().BeTrue();
        cacheControl.MaxAge.Should().Be(TimeSpan.FromHours(1));
    }

    [Fact]
    public async Task Get_ReturnsThreeZeroFourWhenIfNoneMatchEqualsCurrentETag()
    {
        await using ArchLucidApiFactory factory = new();
        HttpClient client = factory.CreateClient();

        HttpResponseMessage seed = await client.GetAsync(EndpointPath);
        seed.StatusCode.Should().Be(HttpStatusCode.OK);
        string etag = seed.Headers.ETag!.Tag;

        using HttpRequestMessage conditional = new(HttpMethod.Get, EndpointPath);
        conditional.Headers.TryAddWithoutValidation("If-None-Match", etag);

        HttpResponseMessage cached = await client.SendAsync(conditional);
        cached.StatusCode.Should().Be(HttpStatusCode.NotModified);

        string body = await cached.Content.ReadAsStringAsync();
        body.Should().BeEmpty();
    }

    [Fact]
    public async Task Get_EtagIsContentDrivenAndMatchesEvidencePackEtagComputeOverEmbeddedSources()
    {
        await using ArchLucidApiFactory factory = new();
        HttpClient client = factory.CreateClient();

        HttpResponseMessage response = await client.GetAsync(EndpointPath);
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        string actualEtag = response.Headers.ETag!.Tag;

        EmbeddedResourceEvidencePackSourceProvider provider = new();
        IReadOnlyList<EvidencePackEntry> sources = await provider.GetEntriesAsync();
        string expectedEtag = EvidencePackEtag.Compute(sources);

        actualEtag.Should().Be(expectedEtag,
            "the controller MUST advertise the same SHA-256-derived ETag the builder computes.");
    }

    private static IReadOnlyList<string> ListZipEntryNames(byte[] zipBytes)
    {
        using MemoryStream ms = new(zipBytes);
        using ZipArchive archive = new(ms, ZipArchiveMode.Read);
        return [.. archive.Entries.Select(e => e.FullName)];
    }
}
