<#
.SYNOPSIS
  Builds the canonical Contoso worked-example ROI PDF from the per-tenant value-report DOCX path, plus markdown mirror.

.DESCRIPTION
  1) docker compose --profile full-stack up -d (SQL + API + UI profile used for local demo).
  2) POST /v1/demo/seed (idempotent) under the default dev scope.
  3) POST /v1/value-report/{defaultTenant}/generate with a UTC window that brackets the seeded Contoso demo activity.
  4) Writes a temp DOCX, runs scripts/ops/value_report_docx_extract_to_md.py to refresh docs/go-to-market/WORKED_EXAMPLE_ROI.md autogenerated block.
  5) Converts DOCX to PDF using (in order): LibreOffice soffice, Microsoft Word COM (Windows), or pandoc (requires a PDF engine).

  AgentExecution is expected to be Simulator via ArchLucid.Api appsettings (no live LLM). Do not change the value-report
  endpoint contract — this script is an HTTP client only.

  Determinism: numeric metrics come only from SQL read by the value-report builder for the seeded tenant/window. PDF bytes
  may still vary slightly when using Word COM (fonts/printer drivers); prefer LibreOffice soffice for more stable binaries
  when available.

.PARAMETER ApiBaseUrl
  Root URL of the ArchLucid API (no trailing slash). Default http://localhost:5000 (docker-compose full-stack mapping).

.PARAMETER SkipDocker
  When set, skips docker compose up (use when stack is already running).

.EXAMPLE
  ./scripts/ops/generate-worked-example-roi.ps1
  ./scripts/ops/generate-worked-example-roi.ps1 -ApiBaseUrl "http://localhost:5000" -SkipDocker
#>
[CmdletBinding()]
param(
  [string] $ApiBaseUrl = "http://localhost:5000",
  [switch] $SkipDocker
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$docxTemp = Join-Path $env:TEMP "archlucid-worked-example-value-report.docx"
$pdfOutDocs = Join-Path $repoRoot "docs\go-to-market\WORKED_EXAMPLE_ROI.pdf"
$pdfOutPublic = Join-Path $repoRoot "archlucid-ui\public\WORKED_EXAMPLE_ROI.pdf"
$mdPath = Join-Path $repoRoot "docs\go-to-market\WORKED_EXAMPLE_ROI.md"
$pyExtract = Join-Path $repoRoot "scripts\ops\value_report_docx_extract_to_md.py"
$defaultTenant = "11111111-1111-1111-1111-111111111111"

function Convert-DocxToPdf {
  param(
    [string] $DocxPath,
    [string] $PdfPath
  )

  $soffice = Get-Command soffice -ErrorAction SilentlyContinue

  if ($soffice) {
    $outDir = Split-Path -Parent $PdfPath
    $argList = @("--headless", "--convert-to", "pdf", "--outdir", $outDir, $DocxPath)
    & $soffice.Source @argList
    $leaf = [System.IO.Path]::GetFileNameWithoutExtension($DocxPath) + ".pdf"
    $produced = Join-Path $outDir $leaf

    if (Test-Path $produced) {
      Move-Item -Force $produced $PdfPath
      return
    }
  }

  try {
    $word = New-Object -ComObject Word.Application
    $word.Visible = $false
    $docFull = (Resolve-Path $DocxPath).Path
    $doc = $word.Documents.Open($docFull)
    $banner =
      "Sample (fictional Contoso tenant): numbers come from the seeded value-report DOCX path; not customer ROI. " +
      "Regenerate via scripts/ops/generate-worked-example-roi.ps1.`r"
    $doc.Content.InsertBefore($banner)
    $wdFormatPDF = 17
    $doc.ExportAsFixedFormat($PdfPath, $wdFormatPDF)
    $doc.Close($false)
    $word.Quit()
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($doc) | Out-Null
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($word) | Out-Null
    return
  }
  catch {
    Write-Warning "Word COM conversion failed: $($_.Exception.Message)"
  }

  $pandoc = Get-Command pandoc -ErrorAction SilentlyContinue

  if ($pandoc) {
    & $pandoc.Source @($DocxPath, "-o", $PdfPath)
    return
  }

  throw "Could not convert DOCX to PDF. Install LibreOffice (soffice), Microsoft Word, or pandoc with a working PDF engine."
}

if (-not $SkipDocker) {
  Push-Location $repoRoot
  try {
    docker compose --profile full-stack up -d
  }
  finally {
    Pop-Location
  }

  $deadline = (Get-Date).AddMinutes(8)

  do {
    try {
      $health = Invoke-WebRequest -Uri "$ApiBaseUrl/health/live" -UseBasicParsing -TimeoutSec 5

      if ($health.StatusCode -ge 200 -and $health.StatusCode -lt 300) {
        break
      }
    }
    catch {
      Start-Sleep -Seconds 3
    }

    if ((Get-Date) -gt $deadline) {
      throw "API did not become healthy at $ApiBaseUrl/health/live within the deadline."
    }
  } while ($true)
}

$base = $ApiBaseUrl.TrimEnd("/")

Write-Host "POST $base/v1.0/demo/seed"
$seed = Invoke-WebRequest -Uri "$base/v1.0/demo/seed" -Method Post -UseBasicParsing -TimeoutSec 120

if ($seed.StatusCode -notin @(200, 204)) {
  throw "Demo seed returned HTTP $($seed.StatusCode) (expected 200 or 204)."
}

$from = "2025-03-01T00:00:00.0000000Z"
$to = "2025-04-01T00:00:00.0000000Z"
$genUrl = "$base/v1.0/value-report/$defaultTenant/generate?from=$([uri]::EscapeDataString($from))&to=$([uri]::EscapeDataString($to))"

Write-Host "POST $genUrl"
Invoke-WebRequest -Uri $genUrl -Method Post -UseBasicParsing -TimeoutSec 300 -OutFile $docxTemp

$len = (Get-Item $docxTemp).Length
Write-Host "Wrote DOCX to $docxTemp ($len bytes)"

& python $pyExtract --docx $docxTemp --md $mdPath

Convert-DocxToPdf -DocxPath $docxTemp -PdfPath $pdfOutDocs
Copy-Item -Force $pdfOutDocs $pdfOutPublic

Write-Host "Wrote $pdfOutDocs and $pdfOutPublic"
