"""
Extract value-report DOCX metrics (same paragraph labels as DocxValueReportRenderer) into a markdown fragment.

Used by scripts/ops/generate-worked-example-roi.ps1 so WORKED_EXAMPLE_ROI.md stays aligned with the
per-tenant value-report DOCX bytes (no invented numbers).

Requires: Python 3.11+ (stdlib only).
"""

from __future__ import annotations

import argparse
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET


_NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}


def _docx_plain_text(docx_path: Path) -> str:
    with zipfile.ZipFile(docx_path, "r") as zf:
        entry = zf.getinfo("word/document.xml")
        raw = zf.read(entry)

    root = ET.fromstring(raw)
    parts: list[str] = []

    for paragraph in root.findall(".//w:p", _NS):
        texts = [t.text or "" for t in paragraph.findall(".//w:t", _NS)]
        line = "".join(texts).strip()

        if line:
            parts.append(line)

    return "\n".join(parts)


def _extract_metrics(plain: str) -> dict[str, str]:
    """Pull lines that match DocxValueReportRenderer paragraph prefixes."""

    lines = plain.splitlines()
    wanted_prefixes = (
        "Runs completed (terminal):",
        "Manifests committed:",
        "Governance-class audit events:",
        "Drift / alert-class audit events:",
        "Net score (thumbs up minus thumbs down) in window:",
        "Votes recorded in window:",
        "From committed manifests:",
        "From governance events:",
        "From drift/alert events:",
        "Total (composite):",
        "Window USD (completed runs × model rate):",
        "Annualized hours value (USD):",
        "Annualized LLM cost (USD):",
        "Baseline annual subscription + ops (model doc):",
        "Net annualized value vs baseline (USD):",
        "ROI vs baseline (%):",
    )

    found: dict[str, str] = {}

    for line in lines:
        for prefix in wanted_prefixes:
            if line.startswith(prefix):
                found[prefix] = line[len(prefix) :].strip()

    return found


def _render_markdown_fragment(metrics: dict[str, str]) -> str:
    rows = [
        ("Metric", "Value (from value-report DOCX)"),
        ("Runs completed (terminal)", metrics.get("Runs completed (terminal):", "—")),
        ("Manifests committed", metrics.get("Manifests committed:", "—")),
        ("Governance-class audit events", metrics.get("Governance-class audit events:", "—")),
        ("Drift / alert-class audit events", metrics.get("Drift / alert-class audit events:", "—")),
        ("Finding feedback net score", metrics.get("Net score (thumbs up minus thumbs down) in window:", "—")),
        ("Finding feedback votes", metrics.get("Votes recorded in window:", "—")),
        ("Architect-hours saved (manifests)", metrics.get("From committed manifests:", "—")),
        ("Architect-hours saved (governance)", metrics.get("From governance events:", "—")),
        ("Architect-hours saved (drift/alerts)", metrics.get("From drift/alert events:", "—")),
        ("Architect-hours saved (total)", metrics.get("Total (composite):", "—")),
        ("LLM cost window USD", metrics.get("Window USD (completed runs × model rate):", "—")),
        ("Annualized hours value USD", metrics.get("Annualized hours value (USD):", "—")),
        ("Annualized LLM cost USD", metrics.get("Annualized LLM cost (USD):", "—")),
        ("Baseline annual subscription + ops USD", metrics.get("Baseline annual subscription + ops (model doc):", "—")),
        ("Net annualized value vs baseline USD", metrics.get("Net annualized value vs baseline (USD):", "—")),
        ("ROI vs baseline (%)", metrics.get("ROI vs baseline (%):", "—")),
    ]

    lines_out = ["| " + " | ".join(rows[0]) + " |", "| " + " | ".join(["---"] * len(rows[0])) + " |"]

    for label, value in rows[1:]:
        safe_value = value.replace("|", "\\|")
        lines_out.append(f"| {label} | {safe_value} |")

    return "\n".join(lines_out) + "\n"


def _replace_autogenerated_block(md_path: Path, fragment: str) -> None:
    begin = "<!-- BEGIN_AUTOGENERATED_ROI_MD -->"
    end = "<!-- END_AUTOGENERATED_ROI_MD -->"
    text = md_path.read_text(encoding="utf-8")

    if begin not in text or end not in text:
        raise ValueError(f"Markers {begin!r} and {end!r} must exist in {md_path}.")

    pattern = re.compile(
        re.escape(begin) + r"[\s\S]*?" + re.escape(end),
        re.MULTILINE,
    )
    replacement = f"{begin}\n{fragment.rstrip()}\n{end}"

    updated, count = pattern.subn(replacement, text, count=1)

    if count != 1:
        raise ValueError("Expected exactly one autogenerated block to replace.")

    md_path.write_text(updated, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docx", type=Path, required=True)
    parser.add_argument("--md", type=Path, required=True)
    args = parser.parse_args()

    docx_path: Path = args.docx
    md_path: Path = args.md

    if not docx_path.is_file():
        print(f"DOCX not found: {docx_path}", file=sys.stderr)
        return 2

    plain = _docx_plain_text(docx_path)
    metrics = _extract_metrics(plain)
    fragment = _render_markdown_fragment(metrics)
    _replace_autogenerated_block(md_path, fragment)
    print(f"Updated autogenerated block in {md_path} from {docx_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
