using System.Globalization;
using System.Text;

namespace ArchLucid.Application.Pilots;

/// <summary>
///     Markdown export for sponsor / executive sharing (pairs with JSON from the same <see cref="PilotValueReport" />
///     ).
/// </summary>
public static class PilotValueReportMarkdown
{
    public static string Format(PilotValueReport r)
    {
        ArgumentNullException.ThrowIfNull(r);

        StringBuilder sb = new();

        sb.AppendLine("# ArchLucid pilot value report");
        sb.AppendLine();
        sb.AppendLine("| Field | Value |");
        sb.AppendLine("| --- | --- |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Tenant | `{r.TenantId}` |");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Window (UTC) | `{r.FromUtc:O}` inclusive → `{r.ToUtc:O}` exclusive |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Committed runs | {r.TotalRunsCommitted} |");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Run-detail cap | {r.RunDetailCap} (truncated: {r.RunDetailsTruncated}) |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Audit export truncated | {r.AuditExportTruncated} |");
        sb.AppendLine();

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| Metric | Value |");
        sb.AppendLine("| --- | --- |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Total findings | {r.TotalFindings} |");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"| Avg pipeline completion | {FormatAvgSeconds(r.AveragePipelineCompletionSeconds)} |");

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Recommendations generated (audit) | {r.TotalRecommendationsProduced} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Governance approvals | {r.GovernanceApprovals} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Governance rejections | {r.GovernanceRejections} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Policy pack assignments | {r.PolicyPackAssignments} |");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"| Comparison / drift detections | {r.ComparisonOrDriftDetections} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Pending approvals (now) | {r.GovernancePendingApprovalsNow} |");
        sb.AppendLine();

        sb.AppendLine("## Findings by severity");
        sb.AppendLine();
        sb.AppendLine("| Severity | Count |");
        sb.AppendLine("| --- | --- |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Critical | {r.FindingsBySeverity.Critical} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| High | {r.FindingsBySeverity.High} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Medium | {r.FindingsBySeverity.Medium} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Low | {r.FindingsBySeverity.Low} |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"| Info | {r.FindingsBySeverity.Info} |");
        sb.AppendLine();
        AppendSeverityNote(sb);
        sb.AppendLine();

        sb.AppendLine("## Agent types observed");
        sb.AppendLine();
        sb.AppendLine(string.Join(", ", r.UniqueAgentTypes.Select(static t => $"`{t}`")));
        sb.AppendLine();

        sb.AppendLine("## Committed runs (sample loaded for detail)");
        sb.AppendLine();
        sb.AppendLine("| Run | Created (UTC) | Committed (UTC) | System |");
        sb.AppendLine("| --- | --- | --- | --- |");

        foreach (PilotValueReportRunTimelinePoint row in r.CommittedRunsTimeline)
        {
            string c = row.CommittedUtc is { } cu ? $"`{cu:O}`" : "—";

            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"| `{row.RunId}` | `{row.CreatedUtc:O}` | {c} | {EscapeCell(row.SystemName)} |");
        }

        sb.AppendLine();
        sb.AppendLine("— *Generated by ArchLucid in-product pilot value report.*");

        return sb.ToString();
    }

    private static void AppendSeverityNote(StringBuilder sb)
    {
        sb.AppendLine(
            "> Severity mapping: pipeline `FindingSeverity` uses Critical / High (Error) / Medium (Warning) / Info; `Low` is reserved for future contract extensions.");
    }

    private static string FormatAvgSeconds(double? seconds)
    {
        if (seconds is null)
            return "—";

        double s = seconds.Value;

        if (double.IsNaN(s) || double.IsInfinity(s))
            return "—";

        if (s >= 3600)
            return $"{s / 3600:0.##} h";

        return s >= 60 ? $"{s / 60:0.##} min" : $"{s:0.##} s";
    }

    private static string EscapeCell(string value)
    {
        return string.IsNullOrEmpty(value) ? "—" : value.Replace("|", "\\|", StringComparison.Ordinal);
    }
}
