using System.Diagnostics.CodeAnalysis;

namespace ArchLucid.Cli.Commands;

[ExcludeFromCodeCoverage(Justification = "CLI prints static template text only.")]
internal static class PilotSuccessCriteriaTemplateCommand
{
    public static Task<int> RunAsync()
    {
        const string md = """
            # ArchLucid pilot — success criteria (copy into your charter)

            **Objective:** Validate that ArchLucid reduces architecture review cycle time and produces a durable, auditable golden manifest in your tenant.

            **Scope window:** __________ (start / end dates)

            **Pilot owner (customer):** __________

            **Technical owner (customer):** __________

            ## Success criteria (check all that apply / targets)

            1. **Time-to-first committed manifest:** ≤ _______ business days from SQL + Entra access.
            2. **Operator task completion:** Core pilot checklist on Home completed through artifact review.
            3. **Governance (if in scope):** At least one approval or pre-commit gate scenario exercised with expected audit rows.
            4. **Evidence:** Export ZIP or audit CSV retained for procurement / internal QA.
            5. **Stakeholder read-out:** Sponsor receives first-value Markdown or sponsor pack link.

            ## Out of scope for this pilot (explicit)

            - First-party Jira / ServiceNow connectors (V1.1 candidates per V1_DEFERRED.md)
            - MCP / external agent tool host (V1.1 candidate)
            - Self-serve commerce live keys (V1.1 candidate)

            ## Roll-forward decision

            - **Continue to paid / expand:** criteria met on or before __________
            - **Extend pilot:** reason __________
            - **Stop:** reason __________

            _Generated by `archlucid pilot success-criteria-template` — edit dates and names before circulation._
            """;

        Console.WriteLine(md);

        return Task.FromResult(CliExitCode.Success);
    }
}
