namespace ArchLucid.Core.Configuration;

/// <summary>Operator-facing key registry (see <c>docs/library/CONFIGURATION_REFERENCE.md</c>). Paths use colon notation.</summary>
public static class ConfigurationKeyCatalog
{
  public static IReadOnlyList<ConfigurationKeyEntry> All { get; } = Build();

  private static IReadOnlyList<ConfigurationKeyEntry> Build()
  {
    return new List<ConfigurationKeyEntry>(110)
    {
      E("Hosting", "Hosting:LogStartupConfigurationSummary", M("appsettings", "env"), "true", "—", "Log effective configuration on startup (host).", ConfigKeyRequirementKind.None),
      E("Hosting", "Hosting:Role", M("appsettings", "env"), "Combined", "—", "Api, Worker, or Combined host process.", ConfigKeyRequirementKind.None),
      E("Metering", "Metering:Enabled", M("appsettings", "env"), "false", "—", "Feature metering toggle.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:Secrets:Provider", M("appsettings", "env", "KeyVault ref"), "EnvironmentVariable", "—", "How secrets (connection strings, API keys) are loaded.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:Secrets:KeyVaultUri", M("appsettings", "env", "KeyVault"), "empty", "If Key Vault routing", "Azure Key Vault base URI when the secrets provider needs it.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:Secrets:KeyVaultCacheSeconds", M("appsettings", "env"), "300", "—", "Secret cache duration for Key Vault access.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:StorageProvider", M("appsettings", "env"), "Sql", "—", "InMemory (tests) or Sql; unset defaults to Sql in product rules.", ConfigKeyRequirementKind.None),
      E("ConnectionStrings", "ConnectionStrings:ArchLucid", M("appsettings", "env", "KeyVault", "user secrets"), "see default dev", "When SQL is active", "Primary SQL connection string (required when using Sql storage).", ConfigKeyRequirementKind.WhenDefaultSqlStorage),
      E("ArchLucid", "ArchLucid:Persistence:AllowRlsBypass", M("appsettings", "env"), "false", "—", "Dev-only: bypass SQL row-level security in tests.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:PublicSite:BaseUrl", M("appsettings", "env"), "https://archlucid.com", "—", "Public marketing / operator link base for emails and exports.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:Notifications:TrialLifecycle:Owner", M("appsettings", "env"), "Hosted", "—", "Who runs trial notification emails for this tenant class.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:Enabled", M("appsettings", "env"), "true", "—", "Enables quality gate for agent output.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:StructuralWarnBelow", M("appsettings", "env"), "0.55", "—", "Quality gate warn threshold (structural).", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:SemanticWarnBelow", M("appsettings", "env"), "0.55", "—", "Quality gate warn threshold (semantic).", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:StructuralRejectBelow", M("appsettings", "env"), "0.35", "—", "Quality gate reject (structural).", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:AgentOutput:QualityGate:SemanticRejectBelow", M("appsettings", "env"), "0.35", "—", "Quality gate reject (semantic).", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:Explanation:Aggregate:FaithfulnessFallbackEnabled", M("appsettings", "env"), "true", "—", "Allow fallback when faithfulness is low.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:Explanation:Aggregate:MinSupportRatioToTrustLlmNarrative", M("appsettings", "env"), "0.2", "—", "Minimum support ratio to trust the LLM narrative block.", ConfigKeyRequirementKind.None),
      E("ArchLucid", "ArchLucid:MermaidCli:Enabled", M("appsettings", "env"), "false", "—", "Optionally render Mermaid with external CLI.", ConfigKeyRequirementKind.None),
      E("CosmosDb", "CosmosDb:ConnectionString", M("appsettings", "env", "KeyVault"), "empty", "When using Cosmos", "Optional Cosmos connection when the deployment uses it.", ConfigKeyRequirementKind.None),
      E("CosmosDb", "CosmosDb:DatabaseName", M("appsettings", "env"), "ArchLucid", "—", "Cosmos database name when enabled.", ConfigKeyRequirementKind.None),
      E("CosmosDb", "CosmosDb:GraphSnapshotsEnabled", M("appsettings", "env"), "false", "—", "Store graph snapshots in Cosmos when enabled.", ConfigKeyRequirementKind.None),
      E("CosmosDb", "CosmosDb:AgentTracesEnabled", M("appsettings", "env"), "false", "—", "Store agent traces in Cosmos when enabled.", ConfigKeyRequirementKind.None),
      E("CosmosDb", "CosmosDb:AuditEventsEnabled", M("appsettings", "env"), "false", "—", "Stream audit to Cosmos if configured.", ConfigKeyRequirementKind.None),
      E("HotPathCache", "HotPathCache:Enabled", M("appsettings", "env"), "true", "—", "Hot path cache on/off.", ConfigKeyRequirementKind.None),
      E("HotPathCache", "HotPathCache:Provider", M("appsettings", "env"), "Auto", "—", "Cache backend selection (e.g. Redis, memory, auto).", ConfigKeyRequirementKind.None),
      E("HotPathCache", "HotPathCache:ExpectedApiReplicaCount", M("appsettings", "env"), "1", "—", "Expected number of API replicas (cache coherency hint).", ConfigKeyRequirementKind.None),
      E("HotPathCache", "HotPathCache:AbsoluteExpirationSeconds", M("appsettings", "env"), "60", "—", "Absolute cache TTL in seconds for hot path entries.", ConfigKeyRequirementKind.None),
      E("HotPathCache", "HotPathCache:RedisConnectionString", M("appsettings", "env", "KeyVault"), "empty", "When using Redis for cache", "Redis when Provider selects Redis/Auto+Redis discoverable.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:Mode", M("appsettings", "env"), "Simulator", "—", "Simulator (offline) or Real (calls Azure OpenAI) — see validation rules.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:CompletionClient", M("appsettings", "env"), "omit or Azure", "—", "Echo to skip real LLM; see AgentExecution rules.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:LlmCostEstimation:Enabled", M("appsettings", "env"), "true", "—", "Token cost heuristics for telemetry.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:LlmCostEstimation:InputUsdPerMillionTokens", M("appsettings", "env"), "0.5", "—", "Cost model input (USD per 1M tokens).", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:LlmCostEstimation:OutputUsdPerMillionTokens", M("appsettings", "env"), "1.5", "—", "Cost model output (USD per 1M tokens).", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:TraceStorage:BlobPersistenceTimeoutSeconds", M("appsettings", "env"), "30", "—", "Timeout for writing trace chunks to durable storage.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:ReferenceEvaluation:Enabled", M("appsettings", "env"), "false", "—", "Reference case evaluation off by default in template.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:ReferenceEvaluation:ReferenceCasesPath", M("appsettings", "env"), "empty", "When reference eval on", "Path to reference case fixtures.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:Resilience:MaxConcurrentHandlers", M("appsettings", "env"), "8", "—", "Parallel agent/LLM handler limit.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:Resilience:PerHandlerTimeoutSeconds", M("appsettings", "env"), "900", "—", "Per job timeout.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:Resilience:LlmCallMaxRetryAttempts", M("appsettings", "env"), "3", "—", "LLM call retries.", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:Resilience:LlmCallBaseDelayMilliseconds", M("appsettings", "env"), "500", "—", "Exponential backoff base (LLM).", ConfigKeyRequirementKind.None),
      E("AgentExecution", "AgentExecution:Resilience:LlmCallMaxDelaySeconds", M("appsettings", "env"), "10", "—", "Maximum delay between LLM retries.", ConfigKeyRequirementKind.None),
      E("AzureOpenAI", "AzureOpenAI:Endpoint", M("appsettings", "env", "KeyVault", "AZURE_OPENAI__Endpoint"), "empty", "When Real and not Echo", "Azure OpenAI resource endpoint (HTTPS).", ConfigKeyRequirementKind.WhenRealLlmNotEcho),
      E("AzureOpenAI", "AzureOpenAI:ApiKey", M("env", "KeyVault", "AZURE_OPENAI__ApiKey"), "empty", "When Real and not Echo", "Client credential for the Azure OpenAI resource (never log).", ConfigKeyRequirementKind.WhenRealLlmNotEcho),
      E("AzureOpenAI", "AzureOpenAI:DeploymentName", M("env", "AZURE_OPENAI__DeploymentName"), "empty", "When Real and not Echo", "Chat/Completion deployment name in Azure OpenAI.", ConfigKeyRequirementKind.WhenRealLlmNotEcho),
      E("AzureOpenAI", "AzureOpenAI:MaxCompletionTokens", M("appsettings", "env"), "0 (4096 default)", "—", "Upper bound; 0 uses product default (see agents pipeline).", ConfigKeyRequirementKind.None),
      E("LlmDailyTenantBudget", "LlmDailyTenantBudget:Enabled", M("appsettings", "env"), "false", "—", "Enforce daily LLM token cap per tenant.", ConfigKeyRequirementKind.None),
      E("LlmDailyTenantBudget", "LlmDailyTenantBudget:MaxTotalTokensPerTenantPerUtcDay", M("appsettings", "env"), "1000000", "When cap on", "Token budget per calendar UTC day.", ConfigKeyRequirementKind.None),
      E("LlmDailyTenantBudget", "LlmDailyTenantBudget:WarnFraction", M("appsettings", "env"), "0.8", "When cap on", "Warn when consumption crosses this fraction of cap.", ConfigKeyRequirementKind.None),
      E("LlmDailyTenantBudget", "LlmDailyTenantBudget:AssumedMaxTotalTokensPerRequest", M("appsettings", "env"), "65536", "When cap on", "Heuristic for reservation math.", ConfigKeyRequirementKind.None),
      E("AgentPrompts", "AgentPrompts:Versions:topology", M("appsettings", "env"), "v2026-04", "—", "Prompt set version: topology pack.", ConfigKeyRequirementKind.None),
      E("AgentPrompts", "AgentPrompts:Versions:cost", M("appsettings", "env"), "v2026-04", "—", "Prompt set version: cost pack.", ConfigKeyRequirementKind.None),
      E("AgentPrompts", "AgentPrompts:Versions:compliance", M("appsettings", "env"), "v2026-04", "—", "Prompt set: compliance pack.", ConfigKeyRequirementKind.None),
      E("AgentPrompts", "AgentPrompts:Versions:critic", M("appsettings", "env"), "v2026-04", "—", "Prompt set: critic pack.", ConfigKeyRequirementKind.None),
      E("SchemaValidation", "SchemaValidation:AgentResultSchemaPath", M("appsettings", "content"), "schemas/...", "—", "On-disk path to the agent result JSON schema.", ConfigKeyRequirementKind.None),
      E("SchemaValidation", "SchemaValidation:GoldenManifestSchemaPath", M("appsettings", "content"), "schemas/...", "—", "Golden manifest JSON schema file.", ConfigKeyRequirementKind.None),
      E("SchemaValidation", "SchemaValidation:EnableDetailedErrors", M("appsettings", "env"), "true", "—", "Verbose schema errors in early validation (dev).", ConfigKeyRequirementKind.None),
      E("ArchLucidAuth", "ArchLucidAuth:Mode", M("appsettings", "env"), "ApiKey", "—", "Default auth story for the template (dev API key, etc.).", ConfigKeyRequirementKind.None),
      E("ArchLucidAuth", "ArchLucidAuth:Authority", M("appsettings", "env"), "empty", "When OIDC in use", "Identity provider authority (OIDC) when that mode is enabled.", ConfigKeyRequirementKind.None),
      E("ArchLucidAuth", "ArchLucidAuth:Audience", M("appsettings", "env"), "empty", "When OIDC in use", "Token audience (OIDC).", ConfigKeyRequirementKind.None),
      E("ArchLucidAuth", "ArchLucidAuth:DevUserId", M("appsettings", "env"), "dev-user", "—", "Principal id for the development loop.", ConfigKeyRequirementKind.None),
      E("ArchLucidAuth", "ArchLucidAuth:DevUserName", M("appsettings", "env"), "Developer", "—", "Display name in dev default principal.", ConfigKeyRequirementKind.None),
      E("ArchLucidAuth", "ArchLucidAuth:DevRole", M("appsettings", "env"), "Admin", "—", "Default role in dev (see security docs).", ConfigKeyRequirementKind.None),
      E("Trial", "Trial:Lifecycle:IntervalMinutes", M("appsettings", "env"), "360", "—", "Trial state machine / email tick interval.", ConfigKeyRequirementKind.None),
      E("Trial", "Trial:Lifecycle:ReadOnlyAfterExpireDays", M("appsettings", "env"), "7", "—", "Days after expiry before read-only state.", ConfigKeyRequirementKind.None),
      E("Trial", "Trial:Lifecycle:ExportOnlyAfterReadOnlyDays", M("appsettings", "env"), "30", "—", "Transition to export-only after read-only for this many days.", ConfigKeyRequirementKind.None),
      E("Trial", "Trial:Lifecycle:PurgeAfterExportOnlyDays", M("appsettings", "env"), "60", "—", "Hard delete delay after export-only (policy).", ConfigKeyRequirementKind.None),
      E("Trial", "Trial:Lifecycle:HardPurgeMaxRowsPerStatement", M("appsettings", "env"), "5000", "—", "Purge batch size (data retention job).", ConfigKeyRequirementKind.None),
      E("Auth", "Auth:Trial:ExternalIdTenantId", M("appsettings", "env"), "empty", "When trial IdP", "B2C / external tenant id mapping for self-service sign-up.", ConfigKeyRequirementKind.None),
      E("Auth", "Auth:Trial:LocalIdentity:JwtPrivateKeyPemPath", M("appsettings", "env"), "empty", "When local IdP", "PEM for HS/RS local JWT signing (path).", ConfigKeyRequirementKind.None),
      E("Auth", "Auth:Trial:LocalIdentity:JwtIssuer", M("appsettings", "env"), "empty", "When local IdP", "Local JWT issuer string.", ConfigKeyRequirementKind.None),
      E("Auth", "Auth:Trial:LocalIdentity:JwtAudience", M("appsettings", "env"), "empty", "When local IdP", "Local JWT audience.", ConfigKeyRequirementKind.None),
      E("Auth", "Auth:Trial:LocalIdentity:AccessTokenLifetimeMinutes", M("appsettings", "env"), "60", "—", "Access token TTL for local auth.", ConfigKeyRequirementKind.None),
      E("Cors", "Cors:AllowedOrigins:0", M("appsettings", "env", "Cors__*"), "http://localhost:3000", "—", "First allowed origin; additional indices use 1,2,… in JSON.", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:Registration:PermitLimit", M("appsettings", "env"), "5", "—", "Throttling: registration path.", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:Registration:WindowMinutes", M("appsettings", "env"), "60", "—", "Registration throttling window.", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:FixedWindow:PermitLimit", M("appsettings", "env"), "60", "—", "Default fixed window permit cap.", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:FixedWindow:WindowMinutes", M("appsettings", "env"), "1", "—", "Fixed window length in minutes.", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:Replay:Light:PermitLimit", M("appsettings", "env"), "60", "—", "Light replay throttling (see policies).", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:Replay:Light:WindowMinutes", M("appsettings", "env"), "1", "—", "Window for light replay throttling.", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:Replay:Heavy:PermitLimit", M("appsettings", "env"), "15", "—", "Heavy replay throttling (expensive paths).", ConfigKeyRequirementKind.None),
      E("RateLimiting", "RateLimiting:Replay:Heavy:WindowMinutes", M("appsettings", "env"), "1", "—", "Window for heavy replay throttling.", ConfigKeyRequirementKind.None),
      E("Authentication", "Authentication:ApiKey:Enabled", M("appsettings", "env"), "false", "—", "Static X-Api-Key authentication — see `Authentication` startup rules for key material.", ConfigKeyRequirementKind.None),
      E("Authentication", "Authentication:ApiKey:DevelopmentBypassAll", M("appsettings", "env"), "false", "—", "DANGER: only for dev — bypass key checks. Must be off in production.", ConfigKeyRequirementKind.None),
      E("Authentication", "Authentication:ApiKey:AdminKey", M("env", "KeyVault", "user secrets"), "null in template", "If enabled (see custom rule: at least one of Admin/Read keys)", "High-privilege API key value when `Enabled` (never print in CLI; presence only).", ConfigKeyRequirementKind.None),
      E("Authentication", "Authentication:ApiKey:ReadOnlyKey", M("env", "KeyVault", "user secrets"), "null in template", "If enabled (see at least one key rule)", "Read-tier API key when `Enabled` (secret).", ConfigKeyRequirementKind.None),
      E("Billing", "Billing:Provider", M("appsettings", "env"), "Stripe", "—", "Billing integrator: Stripe, marketplace, etc.", ConfigKeyRequirementKind.None),
      E("Billing", "Billing:Stripe:SecretKey", M("env", "KeyVault"), "empty", "Production billing", "Stripe live/test secret; required for paid flows in production.", ConfigKeyRequirementKind.WhenProduction),
      E("Billing", "Billing:Stripe:WebhookSigningSecret", M("env", "KeyVault"), "empty", "Production", "Validates `Stripe-Signature` on the webhook path.", ConfigKeyRequirementKind.WhenProduction),
      E("Billing", "Billing:Stripe:PublishableKey", M("appsettings", "env", "KeyVault"), "empty", "When checkout UI in app", "Publishable key (non-secret but still not echoed by CLI in raw form here).", ConfigKeyRequirementKind.None),
      E("Billing", "Billing:Stripe:PriceIdTeam", M("appsettings", "env"), "empty", "When using Stripe", "Default price for Team SKU.", ConfigKeyRequirementKind.None),
      E("Billing", "Billing:AzureMarketplace:LandingPageUrl", M("appsettings", "env"), "empty", "When marketplace GA in prod", "Azure marketplace landing (production checks when GA).", ConfigKeyRequirementKind.WhenProduction),
      E("Billing", "Billing:AzureMarketplace:MarketplaceOfferId", M("appsettings", "env"), "empty", "When marketplace GA in prod", "Commercial marketplace offer id.", ConfigKeyRequirementKind.WhenProduction),
      E("LlmPromptRedaction", "LlmPromptRedaction:Enabled", M("appsettings", "env"), "true", "—", "Redact prompts in logging/traces.", ConfigKeyRequirementKind.None),
      E("LlmPromptRedaction", "LlmPromptRedaction:ReplacementToken", M("appsettings", "env"), "[REDACTED]", "—", "Replacement for redacted span.", ConfigKeyRequirementKind.None),
      E("Demo", "Demo:Enabled", M("appsettings", "env"), "false", "—", "In-product demo / synthetic paths.", ConfigKeyRequirementKind.None),
      E("Demo", "Demo:SeedOnStartup", M("appsettings", "env"), "false", "—", "Seeds the Contoso path when demo is on (see ops guide).", ConfigKeyRequirementKind.None),
      E("DeveloperExperience", "DeveloperExperience:EnableApiExplorer", M("appsettings", "env"), "false", "—", "Exposes extra OpenAPI/Scalar in non-prod (see security note).", ConfigKeyRequirementKind.None),
      E("DataConsistency", "DataConsistency:OrphanProbeEnabled", M("appsettings", "env"), "true", "—", "Background data consistency scan.", ConfigKeyRequirementKind.None),
      E("DataConsistency", "DataConsistency:OrphanProbeIntervalMinutes", M("appsettings", "env"), "60", "—", "Orphan scan cadence.", ConfigKeyRequirementKind.None),
      E("DataConsistency", "DataConsistency:Enforcement:Mode", M("appsettings", "env"), "Warn", "—", "Warn|Enforce for auto-remediation posture.", ConfigKeyRequirementKind.None),
      E("DataConsistency", "DataConsistency:Enforcement:MaxRowsPerBatch", M("appsettings", "env"), "500", "When enforced", "Safer cap per remediation batch.", ConfigKeyRequirementKind.None),
      E("DataConsistency", "DataConsistency:Enforcement:AlertThreshold", M("appsettings", "env"), "1", "—", "Orphan count threshold to page operators.", ConfigKeyRequirementKind.None),
      E("DataConsistency", "DataConsistency:Enforcement:AutoQuarantine", M("appsettings", "env"), "false", "—", "If true, auto quarantine (must be off until approved).", ConfigKeyRequirementKind.None),
      E("AzureDevOps", "AzureDevOps:Enabled", M("appsettings", "env"), "false", "—", "Enables work-item / PR status integration.", ConfigKeyRequirementKind.None),
      E("AzureDevOps", "AzureDevOps:Organization", M("appsettings", "env", "KeyVault ref"), "empty", "If ADO on", "DevOps org name (non-secret, still presence-checked).", ConfigKeyRequirementKind.None),
      E("AzureDevOps", "AzureDevOps:Project", M("appsettings", "env"), "empty", "If ADO on", "Project in Azure DevOps.", ConfigKeyRequirementKind.None),
      E("AzureDevOps", "AzureDevOps:PersonalAccessToken", M("env", "KeyVault"), "empty", "If ADO on", "PAT for the integration (secret).", ConfigKeyRequirementKind.None),
      E("Serilog", "Serilog:MinimumLevel:Default", M("appsettings", "env"), "Information", "—", "Serilog default minimum (host logging).", ConfigKeyRequirementKind.None),
      E("Logging", "Logging:LogLevel:Default", M("appsettings", "env"), "Information", "—", "Microsoft logger default (framework).", ConfigKeyRequirementKind.None),
      E("Observability", "Observability:Otlp:Enabled", M("appsettings", "env"), "false", "—", "Export OpenTelemetry to OTLP collector (host).", ConfigKeyRequirementKind.None),
      E("Observability", "Observability:Otlp:Endpoint", M("env", "KeyVault"), "empty", "If OTLP enabled", "OTLP base URL; required when `Observability:Otlp:Enabled` is true.", ConfigKeyRequirementKind.WhenOtlpEnabled),
      E("Email", "Email:Provider", M("appsettings", "env"), "Noop", "—", "Noop, Smtp, or Azure Communication Services (see `Email` namespace).", ConfigKeyRequirementKind.None),
      E("Email", "Email:AzureCommunicationServicesEndpoint", M("env", "KeyVault"), "empty", "If ACS for email in prod", "Azure Communication Services **Email** resource endpoint (HTTPS) when that provider is selected (see validation).", ConfigKeyRequirementKind.WhenAcsEmail),
    }.AsReadOnly();
  }

  /// <summary>CLI-only “keys” (env / archlucid.json) — excluded from the API <c>config-summary</c> list.</summary>
  public static IReadOnlyList<ConfigurationKeyEntry> CliLocalOnly { get; } = new List<ConfigurationKeyEntry>(4)
  {
    E("Environment", "ASPNETCORE_ENVIRONMENT", M("env", "launchSettings", "Service"), "(unset)", "—", "ASPNETCORE_ / DOTNET_ENVIRONMENT — cluster role for startup validation. Checked via environment variable, not appsettings path.", ConfigKeyRequirementKind.None),
    E("CLI", "ARCHLUCID_API_URL", M("env", "archlucid.json"), "http://localhost:5128 (default)", "When using the CLI", "Resolves the API base URL; not consumed by the API process.", ConfigKeyRequirementKind.None),
    E("CLI", "ARCHLUCID_API_KEY", M("env", "archlucid.json (optional)"), "empty", "If calling protected admin routes from CLI", "Maps to `X-Api-Key`; never shown by <c>config check</c>.", ConfigKeyRequirementKind.None),
  }.AsReadOnly();

  private static string[] M(params string[] s) => s;

  private static ConfigurationKeyEntry E(
    string section,
    string path,
    IReadOnlyList<string> src,
    string? def,
    string req,
    string desc,
    ConfigKeyRequirementKind r) => new(
    section, path, src, def, req, desc, r);
}
